# Generated by Django 3.0.2 on 2020-04-15 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('minutes', models.IntegerField()),
            ],
            options={
                'ordering': ['minutes'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('notify_phone', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_desktop', models.BooleanField(default=False)),
                ('on_call', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=5.0)),
                ('numberOfRatings', models.IntegerField(default=1)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quick_tutor.Profile')),
                ('courses', models.ManyToManyField(to='quick_tutor.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('share_phone', models.BooleanField(default=False)),
                ('share_email', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=5.0)),
                ('numberOfRatings', models.IntegerField(default=1)),
                ('latitute', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quick_tutor.Profile')),
                ('courses', models.ManyToManyField(to='quick_tutor.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('location', models.CharField(max_length=50)),
                ('state', models.IntegerField(choices=[(0, 'Open'), (1, 'Accepted'), (2, 'Timing'), (3, 'Complete')], default=0)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_stop', models.DateTimeField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_tutor.Course')),
                ('length', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick_tutor.Length')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quick_tutor.Student')),
                ('tutor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick_tutor.Tutor')),
            ],
        ),
    ]
